spring:
    application:
        name: sugyo
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 11MB

    # Database Configuration
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver

    # JPA Configuration
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: none
        show-sql: false
        properties:
            hibernate:
                format_sql: true
    jwt:
        access-token-validity-in-ms: 360000000
        refresh-token-validity-in-ms: 604800000

cors:
    allowed-origins:

# SWAGGER CONFIG
server:
    forward-headers-strategy: framework

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        url: /v3/api-docs

logging:
    level:
        root: INFO
        store.sugyo: DEBUG
