name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'gradle'

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 코드 받기
            cd /home/ubuntu || git clone https://github.com/2025-sugyo/backend.git /home/ubuntu/backend
            cd /home/ubuntu/backend
            git pull origin main
            
            # 빌드
            chmod +x gradlew
            ./gradlew clean build -x test --no-daemon
            
            # Docker 이미지 빌드
            docker build -t sugyo-backend:latest .
            
            # 기존 컨테이너 교체
            docker stop springboot-app || true
            docker rm springboot-app || true
            
            docker run -d \
              --name springboot-app \
              --network infra_app-network \
              --env-file /home/ubuntu/infra/.env \
              --restart unless-stopped \
              -p 8081:8080 \
              sugyo-backend:latest